### ISSUE TITLE
[Feature Request] System.Text.Json.JsonObject is not supported

### ISSUE THREAD

**Issue by warappa** [koculu/Topaz#21] opened 2023-10-16 15:54 UTC
**Describe the bug**
Using Topaz with `System.Text.Json` namespace types like `JsonValue`/`JsonArray`/`JsonObject` doesn't work as of now. When testing with `JsonObject` I didn't get an error, but also didn't get the right result.

**Expected behavior**
The code below should return `123`, but returns `null` instead.

**To Reproduce**
```csharp
var engine = new TopazEngine();

// JsonObject does not work
var jObject = (JsonObject)JsonObject.Parse("""
    { "a": {"b": "123" }}
    """);

// TestDto does work
//var jObject = new TestDto();

engine.SetValue("ob", jObject);

var result = engine.ExecuteExpression("ob.a.b");
Console.WriteLine($"'{result}'");

public class TestDto
{
    public TestAnotherDto a { get; set; } = new TestAnotherDto { b = 123 };
}

public class TestAnotherDto
{
    public int b { get; set; }
}
```

**Desktop**
- Operating System: Windows
- Topaz Version: 1.3.6

**Comment by koculu** [comment] 2023-10-17 07:06
Thanks @warappa for reporting this issue.
My short note:
This is not a bug but a feature request. Currently Topaz does not implement specific handling of JsonObjects.

Could you test if the following solution works for you?
```cs
var jObject = new JSONObject().parse("""
    { "a": {"b": "123" }}
    """);
engine.SetValue("ob", jObject);
engine.ExecuteExpression("ob.a.b");
````

Alternatively, you could write your own JsonElement converter and use it before exposing objects into Topaz Engine runtime.

There is an internal class for converting any JsonElement into JsObject.
Please see[ `Tenray.Topaz.API.JsonElementJsObjectConverter`](https://github.com/koculu/Topaz/blob/main/src/Topaz/API/object/normal/JsonElementJsObjectConverter.cs)

**Comment by warappa** [comment] 2023-10-17 07:49
Sorry, I also changed this for feature request.

Yes, your code works with `JSONObject`. As I work with `System.Text.Json.JsonObject` I will have to try the converter way. My (untested) concern is, that this conversion may lead to other issues (bad performance, manipulating just a copy instead of the real thing,...).

How realistic do you see it to support `System.Text.Json` types natively?

**Comment by koculu** [comment] 2023-10-17 19:21
You didn't encounter any errors with this call: `engine.ExecuteExpression("ob.a.b");`

This is because the `engine.Options.AllowNullReferenceMemberAccess` option is enabled by default. 

If you wish to receive null reference exceptions, you can disable this option

**Comment by koculu** [comment] 2023-10-17 20:01
Topaz configurable interfaces enables creating custom behavior for specific types.

The following is a draft sample that routes property access to JsonObject without converting them.
It is not a complete sample but just a draft to give the idea. 
Adding additional proxy implementations for other Json classes are needed and edge cases are not handled.

```cs

var engine = new TopazEngine();
engine.ObjectProxyRegistry.AddObjectProxy(typeof(JsonObject), new JsonObjectProxy());
        
public class JsonObjectProxy : IObjectProxy
{
    public bool TryGetObjectMember(object instance, object member, out object value, bool isIndexedProperty = false)
    {
        value = null;
        if (instance is not JsonObject jsonObj)
        {
            return false;
        }

        if (isIndexedProperty)
        {
            // TODO: implement indexed property access.
            return false;
        }

        var memberName = member?.ToString() ?? "null";
        if (!jsonObj.TryGetPropertyValue(memberName, out var jsonNode))
        {
            return false;
        }

        try
        {
            value = jsonNode.AsObject();
            return true;
        }
        catch
        {
        }

        try
        {
            value = jsonNode.AsValue();
            return true;
        }
        catch
        {
        }

        try
        {
            value = jsonNode.AsArray();
            return true;
        }
        catch
        {
        }
        return false;
    }

    public bool TrySetObjectMember(object instance, object member, object value, bool isIndexedProperty = false)
    {
        throw new NotImplementedException();
    }
}
```

For other extension opportunities, please refer to [TopazEngineSetup](https://github.com/koculu/Topaz/blob/main/src/Topaz/TopazEngineSetup.cs)

**Comment by koculu** [comment] 2023-10-21 17:05
I am closing this feature request in alignment with the Open-Closed Principle, one of the fundamental principles of SOLID design. 

Topaz does not directly implement or maintain code for specific libraries; instead, it offers powerful extension capabilities for users to integrate and customize functionality as needed.

**Closed by koculu** 2023-10-21 17:05 UTC
Labels: enhancement, wontfix
