### ISSUE TITLE
[Feature Request] Followup to 18: hasOwnProperty

### ISSUE THREAD

**Issue by warappa** [koculu/Topaz#20] opened 2023-10-16 15:46 UTC
**Describe the bug**
The example I had shown you in #18 works, but `hasOwnProperty` is still missing functionality. In JavaScript, `hasOwnProperty` works on **_any_** object, no matter what it is.

**Expected behavior**
`hasOwnProperty` should work for **_any_** object, regardless if it implements `ConcurrentJsObject.cs` or `IDictionary` or something else. To do this it may even utilize reflection if it has to.

**Reproduction**
Given a class like
```csharp
public class TestDto
{
    public int SomeProperty { get; set; }
}
``` 
running the following code should return `true`
```csharp
var engine = new TopazEngine();
var someObject = new TestDto { SomeProperty = 123 };

engine.SetValue("ob", someObject);

var result = engine.ExecuteExpression("ob.hasOwnProperty('SomeProperty')");
Console.WriteLine(result);
```

**Desktop**
- Operating System: **Windows 11**
- Topaz Version: **1.3.7**

**Comment by koculu** [comment] 2023-10-17 06:54
Thanks @warappa for reporting this issue.
My point of view:
- This is not a bug but a feature request.
- Topaz exposed objects can be any dotnet object and Topaz does not enforce full Javascript API comptability.
- There are ways to achieve the desired behavior using C# extensions.
Using the Topaz engine AddExtensionMethods you can add any method to any object.
Could you please test the following code?
```cs
public static class TopazObjectExtensions
{
#pragma warning disable IDE1006 // Naming Styles
    public static bool hasOwnProperty(this object obj, string name)
    {
        if (obj == null) return false;
        if (obj is IDictionary dic)
            return dic.Contains(name);
        var prop = typeof(object).GetProperty(name);
        return prop != null;
    }
#pragma warning restore IDE1006 // Naming Styles
}

void TestExtensionMethod()
{
    var engine = new TopazEngine();
    engine.AddExtensionMethods(typeof(TopazObjectExtensions));
    var someObject = new TestDto { SomeProperty = 123 };
    engine.SetValue("someObject", someObject);
    var result = engine.ExecuteExpression("someObject.hasOwnProperty('SomeProperty')");
    Console.WriteLine(result);
}
```

**Comment by warappa** [comment] 2023-10-17 07:38
Sorry, I see I should have picked feature request.

Thank you for the example of the alternative way, I will try it.

**Comment by koculu** [comment] 2023-10-17 20:07
Topaz does as few as possible to keep the engine simple and fast and provides extension points.
Please consider that not all consumers would need fully capable Javascript API.

For all extension opportunities, please refer to [TopazEngineSetup](https://github.com/koculu/Topaz/blob/main/src/Topaz/TopazEngineSetup.cs)

**Comment by koculu** [comment] 2023-10-21 17:19
The dotnet CLR objects exposed in Topaz Runtime are not JavaScript objects and by default they don't implement standard JavaScript object methods.

The [JsObject ](https://github.com/koculu/Topaz/blob/main/src/Topaz/API/object/normal/JsObject.cs) is designed to mimic Javascript Objects and implements a few essential JavaScript object methods.

Users are responsible for providing methods callable by the JavaScript runtime for the exposed CLR objects.

I am closing this feature request because there is a viable method to achieve the desired functionality.

**Closed by koculu** 2023-10-21 17:19 UTC
Labels: enhancement
